#server:
#  port: 3003
#
#spring:
#  datasource:
#    url:
#    username:
#    password:
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
#  application:
#    name: TICKET-SERVICE
